[package]
name = "molniya"
version = "0.1.0"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
flate2 = "1"
mysql = "26.0.1"
dotenvy = "0.15.7"
dirs = "6"